<h1 align="center">BASICS</H1>

In [2]:
import pandas as pd

Q1 Create a Pandas Series using:<BR>
10, 20, 30, 40, 50
Print the Series.

In [3]:
ser=pd.Series([10,20,30,40,50])
print(ser)

0    10
1    20
2    30
3    40
4    50
dtype: int64

Q2 Create a Series using:<BR>
[10, 20, 30, 40, 50]<BR>
Find and print:<BR>
Values,
Index,
Data type,
Size,
Shape.

In [4]:
ser=pd.Series([10,20,30,40,50])
print("values ",ser)
print("INdex ",ser.index)
print("Data type ",ser.dtype)
print("size ",ser.size)
print("shape ",ser.shape)

values  0    10
1    20
2    30
3    40
4    50
dtype: int64
INdex  RangeIndex(start=0, stop=5, step=1)
Data type  int64
size  5
shape  (5,)

Q3. Custom Index<br>
Create a Pandas Series containing:<br>
85, 90, 78, 92<br>
with the index:<br>
Maths, Science, English, Computer

In [5]:
ser=pd.Series([85,90,78,92],index=['Maths','Sci','eng','copm'])
print(ser)

Maths    85
Sci      90
eng      78
copm     92
dtype: int64

Q4. Access Series Values
Using the previous Series:
Access the marks of Science.
Access the marks of Computer.
Access the first two values.

In [6]:
ser=pd.Series([85,90,78,92],index=['maths','sci','eng','comp'])
print("marks of sci",ser["sci"])
print("marks of COMP",ser["comp"])
print("marks of first two",ser[["maths","sci"]])

marks of sci 90
marks of COMP 92
marks of first two maths    85
sci      90
dtype: int64

 Q5. Create a DataFrame

Create a Pandas DataFrame using the following data:

| Name  | Age | Marks |
|-------|-----|-------|
| Rahul | 20  | 85    |
| Aman  | 21  | 78    |
| Priya | 19  | 92    |
| Neha  | 20  | 88    |

In [7]:
data={
    "Name":["Rahul","Aman","Priya","Neha"],
    "Age":[20,21,19,20],
    "Marks":[85,78,92,88]
}
df=pd.DataFrame(data)
df

    Name  Age  Marks
0  Rahul   20     85
1   Aman   21     78
2  Priya   19     92
3   Neha   20     88

Q6. DataFrame Properties<br>
Using the DataFrame from Q5, find:<br>
Number of rows,
Number of columns,
Shape,
Column names,
Index,
Data types.

In [8]:
data={
    "Name":["Rahul","Aman","priya","neha"],
    "Age":[20,21,19,20],
    "Marks":[85,78,92,88]

}
df=pd.DataFrame(data)
print("no of row",df.shape[0])
print("no. of column",df.shape[1])
print("shape",df.shape)
print("column names",df.columns.tolist())
print("index ",df.index)
print("data type",df.dtypes)

no of row 4
no. of column 3
shape (4, 3)
column names ['Name', 'Age', 'Marks']
index  RangeIndex(start=0, stop=4, step=1)
data type Name     object
Age       int64
Marks     int64
dtype: object

Q7. View Data<br>
Using the same DataFrame, display:<br>
First 2 rows,
Last 2 rows,
First 3 rows,
Use appropriate Pandas methods.

In [9]:
data={
     "Name":["Rahul","Aman","priya","neha"],
    "Age":[20,21,19,20],
    "Marks":[85,78,92,88]
}
df=pd.DataFrame(data)
print("First 2 rows =""\n", df.iloc[:2],"\n")

print("last 2 rows" "\n",df.iloc[-2:],"\n")
print("first 3 rows""\n",df.head(3))

First 2 rows =
     Name  Age  Marks
0  Rahul   20     85
1   Aman   21     78

last 2 rows
     Name  Age  Marks
2  priya   19     92
3   neha   20     88

first 3 rows
     Name  Age  Marks
0  Rahul   20     85
1   Aman   21     78
2  priya   19     92

Q8. Select Columns<br>
From the DataFrame, select:<br>
Only Name,
Only Marks,
Name and Marks,

In [10]:
data={
     "Name":["Rahul","Aman","priya","neha"],
    "Age":[20,21,19,20],
    "Marks":[85,78,92,88]
}
df=pd.DataFrame(data)
print("only name =",df['Name'].tolist())
print("only marks =",df['Marks'].tolist())
print("only name and Marks ""\n",df[['Name','Marks']])

only name = ['Rahul', 'Aman', 'priya', 'neha']
only marks = [85, 78, 92, 88]
only name and Marks
     Name  Marks
0  Rahul     85
1   Aman     78
2  priya     92
3   neha     88

Q9. Select Rows<br>
Using .iloc, select:<br>
First row,
Last row,
First 3 rows.

In [11]:
print("first row""\n",df.iloc[:1])
print("last Row""\n",df.iloc[-1:])
print("first 3 rows""\n",df.iloc[:3])

first row
     Name  Age  Marks
0  Rahul   20     85
last Row
    Name  Age  Marks
3  neha   20     88
first 3 rows
     Name  Age  Marks
0  Rahul   20     85
1   Aman   21     78
2  priya   19     92

Q10. Select Using Labels<br>
Set Name as the index.
Then use .loc to access:<br>
Rahul's complete information,
Priya's marks,
Rahul and Neha's information.

In [12]:
df2=df.set_index("Name")
print("Rahul complete info""\n",df2.loc["Rahul"],"\n")
print("priya marks",df2.loc["priya","Marks"],"\n")
print("Rahul and Neha complete info""\n",df2.loc[["Rahul","neha"]],"\n")

Rahul complete info
 Age      20
Marks    85
Name: Rahul, dtype: int64

priya marks 92

Rahul and Neha complete info
        Age  Marks
Name
Rahul   20     85
neha    20     88

<h1 align="center">LEVEL 2 — Filtering & Data Selection

Q11. Filter Students

Using the following DataFrame:

| Name  | Age | Marks |
|:------|----:|------:|
| Rahul | 20  | 85    |
| Aman  | 21  | 78    |
| Priya | 19  | 92    |
| Neha  | 20  | 88    |
| Rohan | 22  | 65    |

**Task:**  
Find all students who scored **more than 80 marks**.

In [13]:
data={
    "Name":["Rahul","Aman","Priya","Neha","Rohan"],
    "Age":[20,21,19,20,22],
    "Marks":[95,78,92,88,65]
    
}
df=pd.DataFrame(data)
df

    Name  Age  Marks
0  Rahul   20     95
1   Aman   21     78
2  Priya   19     92
3   Neha   20     88
4  Rohan   22     65

In [14]:
print( df[df["Marks"]>80])

    Name  Age  Marks
0  Rahul   20     95
2  Priya   19     92
3   Neha   20     88

Q12. Multiple Conditions<br>
Find students who:<br>
scored more than 80,
AND are younger than 21

In [15]:
print("scored more than 80 AND are younger than 21")
print(df[(df["Marks"]>80) & (df["Age"]<21)])

scored more than 80 AND are younger than 21
    Name  Age  Marks
0  Rahul   20     95
2  Priya   19     92
3   Neha   20     88

Q13. Filter Using OR<br>
Find students who are:<br>
younger than 20,
OR scored more than 90.

In [16]:
print("students who are younger than 20 OR scored more than 90.")
print(df[(df["Age"]<20) | (df["Marks"]>90)])

#METHOD 2(QUERY METHOD)
print(df.query("Marks>90 | Age<20"))

students who are younger than 20 OR scored more than 90.
    Name  Age  Marks
0  Rahul   20     95
2  Priya   19     92
    Name  Age  Marks
0  Rahul   20     95
2  Priya   19     92

Q14. Find Maximum Marks<br>
Find:<br>
Highest marks,
Student who obtained the highest marks,
Row containing the highest marks.

In [17]:
print("Highest Marks",df["Marks"].max())
print("student who securec highest marks:",df.loc[df["Marks"].idxmax(),"Name"],"\n")

print("row containg highest marks")
print(df.loc[[df["Marks"].idxmax()]])

Highest Marks 95
student who securec highest marks: Rahul

row containg highest marks
    Name  Age  Marks
0  Rahul   20     95

Q15. Find Minimum Marks<br>
Find:<br>
Lowest marks,
Student with the lowest marks,
Complete information of that student

In [18]:
print("lowest marks",df["Marks"].min())
print("student with lowest marks:",df.loc[df["Marks"].idxmin() ,"Name"])
print("complet info""\n",df.loc[df["Marks"].idxmin()])#to get output in table like above use extra square bracket it convert to data frame

lowest marks 65
student with lowest marks: Rohan
complet info
 Name     Rohan
Age         22
Marks       65
Name: 4, dtype: object

Q16. Sorting
Sort the DataFrame:<br>
By marks in ascending order,
By marks in descending order,
By age and then marks.

In [19]:
df2=df.copy()#we use copy 
print("Marks in Ascending")
print(df2.sort_values("Marks"))

print("\n""Marks in Descending")
print(df2.sort_values("Marks", ascending=False),"\n")

print("by Age then Marks ")
print(df.sort_values(["Age","Marks"]))

Marks in Ascending
    Name  Age  Marks
4  Rohan   22     65
1   Aman   21     78
3   Neha   20     88
2  Priya   19     92
0  Rahul   20     95

Marks in Descending
    Name  Age  Marks
0  Rahul   20     95
2  Priya   19     92
3   Neha   20     88
1   Aman   21     78
4  Rohan   22     65

by Age then Marks
    Name  Age  Marks
2  Priya   19     92
3   Neha   20     88
0  Rahul   20     95
1   Aman   21     78
4  Rohan   22     65

Q17. Add a New Column<br>
Add a column called Passed.<br>
Condition:<br>
Marks >= 40 → Pass<br>
Marks < 40 → Fail

In [20]:
df2["Passed"]=df2["Marks"].apply(lambda x:"Pass" if x >=40 else "Fail")
df2

    Name  Age  Marks Passed
0  Rahul   20     95   Pass
1   Aman   21     78   Pass
2  Priya   19     92   Pass
3   Neha   20     88   Pass
4  Rohan   22     65   Pass

Q18. Create Grade Column<br>
Create a Grade column using:<br>
90+       → A<br>
80–89     → B<br>
70–79     → C<br>
60–69     → D<br>
Below 60  → F<br>

In [21]:
df3=df2.copy()
df3["Grade"]=df3["Marks"].apply(
    lambda x: 
        "A" if x>90 else
        "B" if 80 <= x <= 89 else
        "C" if 70 <= x <=79  else
        "D" if 60 <= x <=69  else
        "F"
        )
df3

    Name  Age  Marks Passed Grade
0  Rahul   20     95   Pass     A
1   Aman   21     78   Pass     C
2  Priya   19     92   Pass     A
3   Neha   20     88   Pass     B
4  Rohan   22     65   Pass     D

<h1 align="center">LEVEL 3  Data Cleaning</h1>

Q19. Missing Values <br>
Create this DataFrame:<br>
data = {<br>
    "Name": ["Rahul", "Aman", "Priya", "Neha", "Rohan"],<br>
    "Age": [20, np.nan, 19, 20, np.nan],<br>
    "Marks": [85, 78, np.nan, 88, 65]<br>
}<br>
Find:<br>
Number of missing values in each column,
Total number of missing values,
Rows containing missing values.

In [22]:
import numpy as np
data = {
    "Name": ["Rahul", "Aman", "Priya", "Neha", "Rohan"],
    "Age": [20, np.nan, 19, 20, np.nan],
    "Marks": [85, 78, np.nan, 88, 65]
}
df=pd.DataFrame(data)
df

    Name   Age  Marks
0  Rahul  20.0   85.0
1   Aman   NaN   78.0
2  Priya  19.0    NaN
3   Neha  20.0   88.0
4  Rohan   NaN   65.0

In [23]:
print("totaL No of missing value in each column")
print(df.isnull().sum(),"\n")

print("Total missing value",df.isnull().sum().sum())

print("Rows containg missing value")
print(df[df.isnull().any(axis=1)])

totaL No of missing value in each column
Name     0
Age      2
Marks    1
dtype: int64

Total missing value 3
Rows containg missing value
    Name   Age  Marks
1   Aman   NaN   78.0
2  Priya  19.0    NaN
4  Rohan   NaN   65.0

Q20. Handle Missing Values
Using the same DataFrame:<br>
Replace missing Age with the average age,
Replace missing Marks with the average marks.

In [24]:
df2=df.copy()
avg_age=int(df2["Age"].mean())
df2["Age"]=df2["Age"].fillna(avg_age)
print(df2["Age"].fillna(avg_age))

avg_marks=df2["Marks"].mean()
df2["Marks"]=df2["Marks"].fillna(avg_marks)
print(df2["Marks"].fillna(avg_marks))

0    20.0
1    19.0
2    19.0
3    20.0
4    19.0
Name: Age, dtype: float64
0    85.0
1    78.0
2    79.0
3    88.0
4    65.0
Name: Marks, dtype: float64

In [25]:
df2

    Name   Age  Marks
0  Rahul  20.0   85.0
1   Aman  19.0   78.0
2  Priya  19.0   79.0
3   Neha  20.0   88.0
4  Rohan  19.0   65.0

Q21. Remove Missing Values<br>

Create a DataFrame containing missing values and remove:<br>

Rows containing any missing value,
Columns containing missing values.

Use dropna().

In [26]:
df3=df.copy()
print("After removing rows with missing values:")
df3_rows=df3.dropna()
df3=df3_rows
print(df3_rows ,"\n")

df3_columns=df.dropna(axis=1)
print("After removing columns with missing values:")
print(df3_columns)

After removing rows with missing values:
    Name   Age  Marks
0  Rahul  20.0   85.0
3   Neha  20.0   88.0

After removing columns with missing values:
    Name
0  Rahul
1   Aman
2  Priya
3   Neha
4  Rohan

In [27]:
df3

    Name   Age  Marks
0  Rahul  20.0   85.0
3   Neha  20.0   88.0

Q22. Duplicate Data

Create:

data = {
    "Name": ["Rahul", "Aman", "Priya", "Rahul", "Neha"],
    "Marks": [85, 78, 92, 85, 88]
}

Find and remove duplicate rows.

In [28]:
data={
    
    "Name": ["Rahul", "Aman", "Priya", "Rahul", "Neha"],
    "Marks": [85, 78, 92, 85, 88]
}
df=pd.DataFrame(data)
df2=df.copy()
print("Duplicate data""\n",df[df2.duplicated])

print("\n""duplicates after remove")
df2=df2.drop_duplicates()
df2

Duplicate data
     Name  Marks
3  Rahul     85

duplicates after remove

    Name  Marks
0  Rahul     85
1   Aman     78
2  Priya     92
4   Neha     88

Q23. Replace Values

Given:

df = pd.DataFrame({
    "Name": ["Rahul", "Aman", "Priya"],
    "City": ["Jamshedpur", "Ranchi", "Jamshedpur"]
})

Replace "Jamshedpur" with "Bangalore".

In [29]:
df = pd.DataFrame({
    "Name": ["Rahul", "Aman", "Priya"],
    "City": ["Jamshedpur", "Ranchi", "Jamshedpur"]
})
df

    Name        City
0  Rahul  Jamshedpur
1   Aman      Ranchi
2  Priya  Jamshedpur

In [30]:
df2=df.copy()
df2["City"]=df2["City"].replace("Jamshedpur","Banglore")
df2

    Name      City
0  Rahul  Banglore
1   Aman    Ranchi
2  Priya  Banglore

<div align="center">
<h1>LEVEL 4 — Data Transformation
</div>

Q24. Rename Columns
Given:
student_name,
student_age,
student_marks,<br>
Rename them to:,
Name
Age
Marks

In [31]:
df=pd.DataFrame({
    "Student_name":["Sannidh"],
     "Student_age":[21],
      "Student_marks":[89]
      
})
df
df2=df.copy()
df2=df2.rename(columns={"Student_name" : "Name","Student_age":"Age","Student_marks":"Marks"})

In [32]:
df2

      Name  Age  Marks
0  Sannidh   21     89

Q25. Apply Function<bfr>
Given:<br>
df["Marks"] = [45, 60, 75, 90, 30]<br>
Create a new column Marks_Double by multiplying every mark by 2 using .apply().

In [33]:
df=pd.DataFrame({
    "marks":[45,60,75,90,30]
})
df2=df.copy()
df2["marks_double"]=df2["marks"].apply(lambda x: x*2)
df2

   marks  marks_double
0     45            90
1     60           120
2     75           150
3     90           180
4     30            60

Q26. Map Function
Given:
df["Gender"] = ["M", "F", "M", "F", "M"]
Convert:
M → Male
F → Female
using .map().

In [34]:
df=pd.DataFrame({
    "gender":["M","F","M","M","F"]
})
df2=df.copy()
gender_map={"M":"Male","F":"Female"}
df2=df2["gender"].map(gender_map)
df2

0      Male
1    Female
2      Male
3      Male
4    Female
Name: gender, dtype: object

Q27. Replace Values
Given:
Grade
A
B
A
C
B
Replace:
A → Excellent
B → Good
C → Average

In [35]:
df=pd.DataFrame({
    "grade":["A","B","C","C","B"]
    
})
df
df2=df.copy()
grade_map={"A":"EXCELLENT","B":"GOOD","C":"AVG"}
df2=df2["grade"].map(grade_map)
df2

0    EXCELLENT
1         GOOD
2          AVG
3          AVG
4         GOOD
Name: grade, dtype: object

Q28. Reset Index
Create a DataFrame, filter some rows from it, and reset the index so that it starts from 0.

In [36]:
df=pd.DataFrame({
       "Name": ["Rahul", "Aman", "Priya", "Neha", "Rohit"],
    "Marks": [85, 78, 92, 88, 70]
})
df2=df.copy()
df2=df2[df2["Marks"]>80]

df3=df2.copy()
df3=df3.reset_index(drop=True)

df3

    Name  Marks
0  Rahul     85
1  Priya     92
2   Neha     88

<div align="center">
<h1>LEVEL 5 — Statistical Analysis
</div>

Q29. Basic Statistics
Given:
df["Marks"] = [45, 60, 75, 90, 30, 85, 70]<br>
Find:<br>
Mean,
Median,
Mode,
Standard deviation,
Variance,
Minimum,
Maximum.

In [48]:
df=pd.DataFrame({"Marks" : [45, 60,60, 75, 90, 30, 85, 70]})

mean=df["Marks"].mean()
median=df["Marks"].median()
mode=df["Marks"].mode().tolist()
std_dev=df["Marks"].std()
variance=df["Marks"].var()
min=df["Marks"].min()
max=df["Marks"].max()

print("Mean",mean )
print("Median",median )
print("Mode ",mode )
print("Standard deviation ",std_dev)
print("Variance",variance)
print("Minimum ",min )
print("Maximum",max  )

Mean 64.375
Median 65.0
Mode  [60]
Standard deviation  20.077973005261263
Variance 403.125
Minimum  30
Maximum 90

Q30. Describe Dataset<br>
Create a DataFrame containing student information and use:<br>
df.describe()<br>
Understand what each statistical value represents.

In [55]:
data = {
    "Name": ["Rahul", "Aman", "Priya", "Neha", "Riya"],
    "Age": [20, 21, 19, 22, 20],
    "Marks": [85, 78, 92, 88, 75]
}

df=pd.DataFrame(data)
df.describe()

#| Value     | Meaning                                            |
#| --------- | -------------------------------------------------- |
#| **count** | Total number of non-empty values                   |
#| **min**   | Smallest value                                     |
#| **25%**   | 25% of values are below this value (Q1)            |
#| **50%**   | Middle value / Median (Q2)                         |
#| **75%**   | 75% of values are below this value (Q3)            |
#| **max**   | Largest value                                      |

             Age      Marks
count   5.000000   5.000000
mean   20.400000  83.600000
std     1.140175   7.021396
min    19.000000  75.000000
25%    20.000000  78.000000
50%    20.000000  85.000000
75%    21.000000  88.000000
max    22.000000  92.000000

Q31. Unique Values<br>
Given:<br>
df["City"] = [<br>
    "Jamshedpur",<br>
    "Ranchi",<br>
    "Jamshedpur",<br>
    "Delhi",<br>
    "Ranchi",<br>
    "Delhi"<br>
]<br>
Find:<br>
Unique cities,
Number of unique cities,
Frequency of each city.

In [72]:
df=pd.DataFrame({
    "City" : [
    "Jamshedpur",
    "Ranchi",
    "Jamshedpur",
    "Delhi",
    "Ranchi",
    "Delhi"
]
    })

print("unique city are :",df["City"].unique() )
print("total unique city are :",df["City"].nunique())
print("frequency of each city :""\n",df["City"].value_counts())

unique city are : ['Jamshedpur' 'Ranchi' 'Delhi']
total unique city are : 3
frequency of each city :
 City
Jamshedpur    2
Ranchi        2
Delhi         2
Name: count, dtype: int64

Q32. Value Counts
Given a Gender column:
Male
Female
Male
Male
Female
Female
Male
Find the number of males and females.

In [78]:
df=pd.DataFrame({
"gender":["Male",
"Female",
"Male",
"Male",
"Female",
"Female",
"Male"]
})
df
count=df["gender"].value_counts()
print("total male feamale are ""\n",count)

total male feamale are
 gender
Male      4
Female    3
Name: count, dtype: int64

<h1 align="center" style="color: yellow;">
    🚀 LEVEL 7 — Real Data Science Problems
</h1>

 ⭐ Q37. Student Performance Analysis

 Given Data

| Name  | Math | Science | English |
|:------|-----:|--------:|--------:|
| Rahul | 85 | 78 | 90 |
| Aman  | 72 | 80 | 75 |
| Priya | 95 | 92 | 96 |
| Neha  | 60 | 65 | 70 |
| Rohan | 45 | 55 | 50 |

 Tasks



 1  Find the **average marks of each student** <br>
 2  Find the **average marks of each subject**<br> 
 3  Find the **highest scorer** <br>
 4  Find the **lowest scorer** <br>
 5  Find students with **average marks > 75** <br>
 6  Find the **subject with the highest average** <br>
 7  **Rank students** according to their average marks <br>

In [ ]:
data = {
    "Name": ["Rahul", "Aman", "Priya", "Neha", "Rohan"],
    "Math": [85, 72, 95, 60, 45],
    "Science": [78, 80, 92, 65, 55],
    "English": [90, 75, 96, 70, 50]
}
df=pd.DataFrame(data)
df.to_excel("Student Data.xlsx" ,index=False)
df