<h1 align="center">BASICS</H1>

In [1]:
import pandas as pd

Q1 Create a Pandas Series using:<BR>
10, 20, 30, 40, 50
Print the Series.

In [2]:
ser=pd.Series([10,20,30,40,50])
print(ser)

0    10
1    20
2    30
3    40
4    50
dtype: int64

Q2 Create a Series using:<BR>
[10, 20, 30, 40, 50]<BR>
Find and print:<BR>
Values,
Index,
Data type,
Size,
Shape.

In [3]:
ser=pd.Series([10,20,30,40,50])
print("values ",ser)
print("INdex ",ser.index)
print("Data type ",ser.dtype)
print("size ",ser.size)
print("shape ",ser.shape)

values  0    10
1    20
2    30
3    40
4    50
dtype: int64
INdex  RangeIndex(start=0, stop=5, step=1)
Data type  int64
size  5
shape  (5,)

Q3. Custom Index<br>
Create a Pandas Series containing:<br>
85, 90, 78, 92<br>
with the index:<br>
Maths, Science, English, Computer

In [4]:
ser=pd.Series([85,90,78,92],index=['Maths','Sci','eng','copm'])
print(ser)

Maths    85
Sci      90
eng      78
copm     92
dtype: int64

Q4. Access Series Values
Using the previous Series:
Access the marks of Science.
Access the marks of Computer.
Access the first two values.

In [5]:
ser=pd.Series([85,90,78,92],index=['maths','sci','eng','comp'])
print("marks of sci",ser["sci"])
print("marks of COMP",ser["comp"])
print("marks of first two",ser[["maths","sci"]])

marks of sci 90
marks of COMP 92
marks of first two maths    85
sci      90
dtype: int64

 Q5. Create a DataFrame

Create a Pandas DataFrame using the following data:

| Name  | Age | Marks |
|-------|-----|-------|
| Rahul | 20  | 85    |
| Aman  | 21  | 78    |
| Priya | 19  | 92    |
| Neha  | 20  | 88    |

In [6]:
data={
    "Name":["Rahul","Aman","Priya","Neha"],
    "Age":[20,21,19,20],
    "Marks":[85,78,92,88]
}
df=pd.DataFrame(data)
df

    Name  Age  Marks
0  Rahul   20     85
1   Aman   21     78
2  Priya   19     92
3   Neha   20     88

Q6. DataFrame Properties<br>
Using the DataFrame from Q5, find:<br>
Number of rows,
Number of columns,
Shape,
Column names,
Index,
Data types.

In [7]:
data={
    "Name":["Rahul","Aman","priya","neha"],
    "Age":[20,21,19,20],
    "Marks":[85,78,92,88]

}
df=pd.DataFrame(data)
print("no of row",df.shape[0])
print("no. of column",df.shape[1])
print("shape",df.shape)
print("column names",df.columns.tolist())
print("index ",df.index)
print("data type",df.dtypes)

no of row 4
no. of column 3
shape (4, 3)
column names ['Name', 'Age', 'Marks']
index  RangeIndex(start=0, stop=4, step=1)
data type Name     object
Age       int64
Marks     int64
dtype: object

Q7. View Data<br>
Using the same DataFrame, display:<br>
First 2 rows,
Last 2 rows,
First 3 rows,
Use appropriate Pandas methods.

In [8]:
data={
     "Name":["Rahul","Aman","priya","neha"],
    "Age":[20,21,19,20],
    "Marks":[85,78,92,88]
}
df=pd.DataFrame(data)
print("First 2 rows =""\n", df.iloc[:2],"\n")

print("last 2 rows" "\n",df.iloc[-2:],"\n")
print("first 3 rows""\n",df.head(3))

First 2 rows =
     Name  Age  Marks
0  Rahul   20     85
1   Aman   21     78

last 2 rows
     Name  Age  Marks
2  priya   19     92
3   neha   20     88

first 3 rows
     Name  Age  Marks
0  Rahul   20     85
1   Aman   21     78
2  priya   19     92

Q8. Select Columns<br>
From the DataFrame, select:<br>
Only Name,
Only Marks,
Name and Marks,

In [9]:
data={
     "Name":["Rahul","Aman","priya","neha"],
    "Age":[20,21,19,20],
    "Marks":[85,78,92,88]
}
df=pd.DataFrame(data)
print("only name =",df['Name'].tolist())
print("only marks =",df['Marks'].tolist())
print("only name and Marks ""\n",df[['Name','Marks']])

only name = ['Rahul', 'Aman', 'priya', 'neha']
only marks = [85, 78, 92, 88]
only name and Marks
     Name  Marks
0  Rahul     85
1   Aman     78
2  priya     92
3   neha     88

Q9. Select Rows<br>
Using .iloc, select:<br>
First row,
Last row,
First 3 rows.

In [10]:
print("first row""\n",df.iloc[:1])
print("last Row""\n",df.iloc[-1:])
print("first 3 rows""\n",df.iloc[:3])

first row
     Name  Age  Marks
0  Rahul   20     85
last Row
    Name  Age  Marks
3  neha   20     88
first 3 rows
     Name  Age  Marks
0  Rahul   20     85
1   Aman   21     78
2  priya   19     92

Q10. Select Using Labels<br>
Set Name as the index.
Then use .loc to access:<br>
Rahul's complete information,
Priya's marks,
Rahul and Neha's information.

In [11]:
df2=df.set_index("Name")
print("Rahul complete info""\n",df2.loc["Rahul"],"\n")
print("priya marks",df2.loc["priya","Marks"],"\n")
print("Rahul and Neha complete info""\n",df2.loc[["Rahul","neha"]],"\n")

Rahul complete info
 Age      20
Marks    85
Name: Rahul, dtype: int64

priya marks 92

Rahul and Neha complete info
        Age  Marks
Name
Rahul   20     85
neha    20     88

<h1 align="center">LEVEL 2 — Filtering & Data Selection

Q11. Filter Students

Using the following DataFrame:

| Name  | Age | Marks |
|:------|----:|------:|
| Rahul | 20  | 85    |
| Aman  | 21  | 78    |
| Priya | 19  | 92    |
| Neha  | 20  | 88    |
| Rohan | 22  | 65    |

**Task:**  
Find all students who scored **more than 80 marks**.

In [22]:
data={
    "Name":["Rahul","Aman","Priya","Neha","Rohan"],
    "Age":[20,21,19,20,22],
    "Marks":[95,78,92,88,65]
    
}
df=pd.DataFrame(data)
df

    Name  Age  Marks
0  Rahul   20     95
1   Aman   21     78
2  Priya   19     92
3   Neha   20     88
4  Rohan   22     65

In [23]:
print( df[df["Marks"]>80])

    Name  Age  Marks
0  Rahul   20     95
2  Priya   19     92
3   Neha   20     88

Q12. Multiple Conditions<br>
Find students who:<br>
scored more than 80,
AND are younger than 21

In [25]:
print("scored more than 80 AND are younger than 21")
print(df[(df["Marks"]>80) & (df["Age"]<21)])

scored more than 80 AND are younger than 21
    Name  Age  Marks
0  Rahul   20     95
2  Priya   19     92
3   Neha   20     88

Q13. Filter Using OR<br>
Find students who are:<br>
younger than 20,
OR scored more than 90.

In [30]:
print("students who are younger than 20 OR scored more than 90.")
print(df[(df["Age"]<20) | (df["Marks"]>90)])

#METHOD 2(QUERY METHOD)
print(df.query("Marks>90 | Age<20"))

students who are younger than 20 OR scored more than 90.
    Name  Age  Marks
0  Rahul   20     95
2  Priya   19     92
    Name  Age  Marks
0  Rahul   20     95
2  Priya   19     92

Q14. Find Maximum Marks<br>
Find:<br>
Highest marks,
Student who obtained the highest marks,
Row containing the highest marks.

In [59]:
print("Highest Marks",df["Marks"].max())
print("student who securec highest marks:",df.loc[df["Marks"].idxmax(),"Name"],"\n")

print("row containg highest marks")
print(df.loc[[df["Marks"].idxmax()]])

Highest Marks 95
student who securec highest marks: Rahul

row containg highest marks
    Name  Age  Marks
0  Rahul   20     95

Q15. Find Minimum Marks<br>
Find:<br>
Lowest marks,
Student with the lowest marks,
Complete information of that student

In [75]:
print("lowest marks",df["Marks"].min())
print("student with lowest marks:",df.loc[df["Marks"].idxmin() ,"Name"])
print("complet info""\n",df.loc[df["Marks"].idxmin()])#to get output in table like above use extra square bracket it convert to data frame

lowest marks 65
student with lowest marks: Rohan
complet info
 Name     Rohan
Age         22
Marks       65
Name: 4, dtype: object

Q16. Sorting
Sort the DataFrame:<br>
By marks in ascending order,
By marks in descending order,
By age and then marks.

In [102]:
df2=df.copy()#we use copy 
print("Marks in Ascending")
print(df2.sort_values("Marks"))

print("\n""Marks in Descending")
print(df2.sort_values("Marks", ascending=False),"\n")

print("by Age then Marks ")
print(df.sort_values(["Age","Marks"]))

Marks in Ascending
    Name  Age  Marks
4  Rohan   22     65
1   Aman   21     78
3   Neha   20     88
2  Priya   19     92
0  Rahul   20     95

Marks in Descending
    Name  Age  Marks
0  Rahul   20     95
2  Priya   19     92
3   Neha   20     88
1   Aman   21     78
4  Rohan   22     65

by Age then Marks
    Name  Age  Marks
2  Priya   19     92
3   Neha   20     88
0  Rahul   20     95
1   Aman   21     78
4  Rohan   22     65

Q17. Add a New Column<br>
Add a column called Passed.<br>
Condition:<br>
Marks >= 40 → Pass<br>
Marks < 40 → Fail

In [105]:
df2["Passed"]=df2["Marks"].apply(lambda x:"Pass" if x >=40 else "Fail")
df2

    Name  Age  Marks Passed
0  Rahul   20     95   Pass
1   Aman   21     78   Pass
2  Priya   19     92   Pass
3   Neha   20     88   Pass
4  Rohan   22     65   Pass

Q18. Create Grade Column<br>
Create a Grade column using:<br>
90+       → A<br>
80–89     → B<br>
70–79     → C<br>
60–69     → D<br>
Below 60  → F<br>

In [114]:
df3=df2.copy()
df3["Grade"]=df3["Marks"].apply(
    lambda x: 
        "A" if x>90 else
        "B" if 80 <= x <= 89 else
        "C" if 70 <= x <=79  else
        "D" if 60 <= x <=69  else
        "F"
        )
df3

    Name  Age  Marks Passed Grade
0  Rahul   20     95   Pass     A
1   Aman   21     78   Pass     C
2  Priya   19     92   Pass     A
3   Neha   20     88   Pass     B
4  Rohan   22     65   Pass     D

<h1 align="center">LEVEL 3  Data Cleaning</h1>